name: Check Changelog

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened, labeled, unlabeled ]
  push:
    branches:
      - master

jobs:
  check_changelog:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'pr release') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Check for a file with the PR number in a sub-directory of the .changes directory" or "no changelog" label.
        run: |
          # Check if we are on master
          if [ "$GITHUB_REF" = "refs/heads/master" ]; then
            echo "On master branch, skipping changelog check."
            exit 0
          fi
          pr_number_file=$(echo $GITHUB_REF | cut -d'/' -f3).md
          if [[ $(find .changes/ -type f -name $pr_number_file -print -quit) ]]; then
            echo "File $pr_number_file exists."
          else
            if [ "${{ contains(github.event.pull_request.labels.*.name, 'no changelog') }}" = "true" ]; then
              echo "No changelog needed."
              exit 0
            else
              echo "File $pr_number_file does not exist."
              exit 1
            fi
          fi
