name: Check Changelog

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened, labeled, unlabeled ]

jobs:
  check_changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Check for a file with the PR number in a sub-directory of the .changes directory" or "no changelog" label.
        run: |
          pr_number_file=$(echo $GITHUB_REF | cut -d'/' -f3).md
          if [[ $(find .changes/ -type f -name $pr_number_file -print -quit) ]]; then
            echo "File $pr_number_file exists."
          else
          if [ "${{ contains(github.event.pull_request.labels.*.name, 'no changelog') }}" = "true" ]; then
            echo "No changelog needed."
            exit 0
          else
            echo "File $pr_number_file does not exist."
            exit 1
          fi