name: Create version

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened, labeled, unlabeled ]

jobs:
  create_version:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'pr release' }}
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create version
        run: |
          echo "Creating version..."
          echo "Version created."